### ISSUE TITLE
Paper, Code, and Dataset

### ISSUE THREAD

**Issue by gqk** [wxzwxzwxz/CL-NeRF#1]
Dear @wxzwxzwxz,

Congratulations on your paper acceptance at NeuralPS! I'm eager to read your work and access your code. Can I request an early draft? I'm also available to help organize and test the code if needed.

Looking forward to your response.

Best regards,

Qiankun Gao

Peking University

Email: gqk@stu.pku.edu.cn

**Comment by wxzwxzwxz** [comment]
Hi @gqk 

Sorry for the late reply. I have been fully occupied with preparations for CVPR, which caused the delay in my reply. I have just updated the [github page](https://wxzwxzwxz.github.io/CL-NeRF), where you can now access the camera-ready paper and the video. However, I kindly request your patience regarding the code, data, and supplementary files, as they will be updated once I have completed the CVPR project. Thanks for your understanding.

**Comment by gqk** [comment]
Thanks for the update. Best regards.

**Comment by gqk** [comment]
Hi, @wxzwxzwxz, 

I am writing to inquire once again about the public release of the code and dataset for the paper "CL-NeRF". 

We are currently conducting research that is closely related to your CL-NeRF work, and we are eager to use your code or dataset to ensure that our comparative experiments are fair and accurate. 

If it is not convenient to publicly release these materials at this time, I would be grateful for the opportunity to discuss this further via email or WeChat.

We look forward to your response and appreciate you taking the time to read this message amidst your busy schedule.

Best regards,

Qiankun Gao

Peking University

Email: gqk@stu.pku.edu.cn
